language: ruby
rvm:
- 2.3.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: HM2nnIywCim1Dh1IXcwZO7fSx7rnep0muPa7ux2HOhEmGU3rHqqQjONP7dr4OJtpvEVaB/qQ+uJHMUqEJE+d+RFZGgWmIn4Of5KjNZ/l+jOoh382RFk4q2vNUn7b8mYDRv4pNOzNuSt1Utd9+t3xD9ObEMIa+QW3Z3Tw3LgGh3lSf0fuUcikyASFvZKxn9Ud4Gh4c7kUuJ8/kMc+4J4q8l0oo/ixtTMgstW/VOMMje4UeWbHenYPDr9R6bkvyBIMLMHXxXEYEiNmvn4buc7N+RkmknPvcIjSgMfbNqWtAaA447KrUTliBp40P154e0fMaSLDq75yO/LzEyC6tKpSgG8S6hGvkG4DSABfkV+c2AScj2uGf3AGF9S7dqHSK46Rue3ZmdS4b3eI4V+tsrTgwSJpcRCEXFewD//WHRZXOlfGrp+E3GrqxgGQspGoBiaIhuwk3FqYhUbETdrJtGF5aL+/3nlhB8xXFhbrr2h3sgoMmgmjltmSOnOV+lVirnYXx301Xfn9sxjvMP4eSECDUF14MKb2lAPhgMYhMvk2M+df8F0wCYhmy7bgisjKEmdEz0kpetoic+l5vmt2YgMXIa9a1oOgUp24xAPlKUz8EFnpWu3xenItkJaG+f6fZR1GGVRHD4fMrXcxOkZE2s6OznZLKrpcrYgeuc+bnKIZvjM=
  app: raemae
  on:
    repo: 012843174/Raemae
